(require 'package)
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (proto (if no-ssl "http" "https")))
  (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t))

(package-initialize)


(defun set-exec-path-from-shell-PATH ()
  (let ((path-from-shell (replace-regexp-in-string
                          "[ \t\n]*$"
                          ""
                          (shell-command-to-string "$SHELL --login -i -c 'echo $PATH'"))))
    (setenv "PATH" path-from-shell)
    (setq eshell-path-env path-from-shell) ; for eshell users
    (setq exec-path (split-string path-from-shell path-separator))))

(when window-system (set-exec-path-from-shell-PATH))

;; Shell at current window

(add-to-list 'display-buffer-alist
             `(,(rx bos "*shell*")
               display-buffer-same-window
               (reusable-frames . visible)))


;;; Nice size for the default window
(defun get-default-height ()
       (/ (- (display-pixel-height) 50)
          (frame-char-height)))

(add-to-list 'default-frame-alist '(width . 200))
(add-to-list 'default-frame-alist (cons 'height (get-default-height)))


(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-names-vector
   ["#212526" "#ff4b4b" "#b4fa70" "#fce94f" "#729fcf" "#e090d7" "#8cc4ff" "#eeeeec"])
 '(coq-shortcut-alist
   (quote
    (("<>" . "⋄")
     ("|>" . "⊳")
     ("\\/" . "∨")
     ("/\\" . "∧")
     ("+O" . "⊕")
     ("-O" . "⊖")
     ("xO" . "⊗")
     ("/O" . "⊘")
     ("|+" . "†")
     ("|++" . "‡")
     ("<=" . "≤")
     ("|-" . "⊢")
     (">=" . "≥")
     ("-|" . "⊣")
     ("||" . "∥")
     ("==" . "≡")
     ("~=" . "≃")
     ("~~~" . "≍")
     ("~~" . "≈")
     ("~==" . "≅")
     ("|<>|" . "⋈")
     ("|=" . "⊨")
     ("=." . "≐")
     ("_|_" . "⊥")
     ("</" . "≮")
     (">=/" . "≱")
     ("=/" . "≠")
     ("==/" . "≢")
     ("~/" . "≁")
     ("~=/" . "≄")
     ("~~/" . "≉")
     ("~==/" . "≇")
     ("<-" . "←")
     ("<=" . "⇐")
     ("->" . "→")
     ("=>" . "⇒")
     ("<->" . "↔")
     ("<=>" . "⇔")
     ("|->" . "↦")
     ("<--" . "⟵")
     ("<==" . "⟸")
     ("-->" . "⟶")
     ("==>" . "⟹")
     ("<==>" . "⟷")
     ("|-->" . "⟼")
     ("<--" . "←⎯")
     ("<-->" . "⟷")
     ("<<" . "⟪")
     ("[|" . "⟦")
     (">>" . "⟫")
     ("|]" . "⟧")
     ("``" . "”")
     ("''" . "“")
     ("--" . "–")
     ("---" . "—")
     ("''" . "″")
     ("'''" . "‴")
     ("''''" . "⁗")
     (":=" . "≔")
     ("\\int" . "ℤ")
     ("\\rat" . "ℚ")
     ("\\complex" . "ℂ")
     ("\\euro" . "€")
     ("\\yen" . "¥")
     ("\\cent" . "¢"))))
 '(coq-token-symbol-map
   (quote
    (("alpha" "α")
     ("beta" "β")
     ("gamma" "γ")
     ("delta" "δ")
     ("epsilon" "ε")
     ("zeta" "ζ")
     ("eta" "η")
     ("theta" "θ")
     ("iota" "ι")
     ("kappa" "κ")
     ("lambda" "λ")
     ("mu" "μ")
     ("nu" "ν")
     ("xi" "ξ")
     ("pi" "π")
     ("rho" "ρ")
     ("sigma" "σ")
     ("tau" "τ")
     ("upsilon" "υ")
     ("phi" "ϕ")
     ("chi" "χ")
     ("psi" "ψ")
     ("omega" "ω")
     ("Gamma" "Γ")
     ("Delta" "Δ")
     ("Theta" "Θ")
     ("Lambda" "Λ")
     ("Xi" "Ξ")
     ("Pi" "Π")
     ("Sigma" "Σ")
     ("Upsilon" "Υ")
     ("Phi" "Φ")
     ("Psi" "Ψ")
     ("Omega" "Ω")
     ("forall" "∀")
     ("exists" "∃")
     ("nat" "ℕ" type)
     ("complex" "ℂ" type)
     ("real" "ℝ" type)
     ("int" "ℤ" type)
     ("rat" "ℚ" type)
     ("bool" "B" underline type)
     ("false" "false" bold sans)
     ("true" "true" bold sans)
     ("WHILE" "WHILE" bold sans)
     ("DO" "DO" bold sans)
     ("END" "END" bold sans)
     ("SKIP" "SKIP" bold sans)
     ("THEN" "THEN" bold sans)
     ("ELSE" "ELSE" bold sans)
     ("IFB" "IFB" bold sans)
     ("FI" "FI" bold sans)
     ("{{" "⦃" bold)
     ("}}" "⦄" bold)
     ("lhd" "⊲")
     ("rhd" "⊳")
     ("<=" "≤")
     (">=" "≥")
     ("=>" "⇒")
     ("->" "→")
     ("<-" "←")
     ("<->" "↔")
     ("++" "⧺")
     ("<<" "《")
     (">>" "》")
     ("===" "≡")
     ("=/=" "≢")
     ("=~=" "≅")
     ("==b" "≡")
     ("<>b" "≢")
     ("-->" "⟹-")
     ("++>" "⟹+")
     ("==>" "⟹")
     (":=" "≔")
     ("|-" "⊢")
     ("<>" "≠")
     ("-|" "⊣")
     ("\\/" "∨")
     ("/\\" "∧")
     ("~" "¬")
     ("============================" "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯" bold tactical))))
 '(custom-enabled-themes (quote (tsdh-dark)))
 '(package-selected-packages (quote (projectile neotree proof-general))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

;; Auto-rename new eww buffers
(defun xah-rename-eww-hook ()
  "Rename eww browser's buffer so sites open in new page."
  (rename-buffer "eww" t))

(add-hook 'eww-mode-hook #'xah-rename-eww-hook)
